# Generated by Django 2.0.10 on 2019-01-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
